# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todo_rails4_angularjs_development
  pool: 5
  username: root
  password: Jiajia25
  host: localhost
  port: 3306
  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: todo_rails4_angularjs,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todo_rails4_angularjs__test
  pool: 5
  username: root
  password: Jiajia25
  host: localhost
  port: 3306 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todo_rails4_angularjs_production
  pool: 5
  username: root
  password: Jiajia25
  host: localhost
  port: 3306 
